### PR TITLE
Improve book container and standardize add/clip commands

### PR DESCRIPTION
**Pull request by craigleat**
It's best to use relative paths in index.html, then the book can be hosted from anywhere.

### CODE REVIEW

**Comment by marvindanig** [comment]
Local credentials are preserved by design on `$ bookiza update`. 

I'm not sure if we're gonna need code to handle [this](https://github.com/bookiza/bookiza/pull/6/commits/564bed15f2a3cd4c5d4035590b5e9f632c622848) at all. Was it that publishing to bubblin did not work normally after update on your machine (linux)?

**Comment by craigleat** [comment]
Hey Marvin,
I don't see how local credentials can be preserved **on the local**. An update executes "npm uninstall -g bookiza" completely removing the bookiza folder including API token. I have to register again after every update to populate the credentials. Re-registering is a pain and the proposed code avoids this.

Ps The proposed patch only lifts the credentials from .bookizarc and inserts them into the newly installed version from npm. This allows the file format to change as the software evolves.

**Comment by craigleat** [comment]
.bookizarc is installed globally on my machine. This is likely to cause issues on a multi user machine and it would be better to install the credentials file in each user's home folder.

**Comment by marvindanig** [comment]
Okay. What was the last version of bookiza you were on before the update? 

Version 0.0.8 onwards bookiza's "arc" has been saved at the OS level root (See [line 49](https://github.com/bookiza/bookiza/blob/15cdd3d87f5bdd4f60c91e56f1e62362084a52c9/lib/register.js)), which kind of takes care of credential preservation at the safest spot of the machine. It draws on a parallel with how bash_profiles/online registries usually work. 

Multiuser machines is an interesting situation to consider; I will take a look into it but in either case we would not need the updater to handle the arc or to preserve the credentials programmatically. It'd be bad design if we have to add additional responsibilities to the module update function -- especially, if in future we adopt automatic updates.

**Comment by marvindanig** [comment]
Can you resubmit this PR with changes up to [dc08370](https://github.com/bookiza/bookiza/pull/6/commits/dc08370708401f6211732c36ac80c79b22456efe)?

**Comment by craigleat** [comment]
Thanks for the discussion, this helped clarify some things.

I believe [eb0b254](https://github.com/bookiza/bookiza/pull/6/commits/eb0b254947e12f2b53559421793aab85d932a8c6) resolves the concerns with multiple users.

**Comment by marvindanig** [comment]
Looks good! I'll sit on these PRs in sometime. Meanwhile, have you tested these changes on windows and mac-os? I guess there will also be updates to the documentation for `add()` & `clip()` methods each. 

Ideally, it'd be nice to introduce a comprehensive test suite around here now and lead it up to CI to pass the builds in future. If you're interested in testing/integration feel free to open an [issue](https://github.com/bookiza/bookiza/issues) to start a discussion on hows and whats of it.  

Thanks for submitting the PRs!

**Comment by craigleat** [comment]
> have you tested these changes on windows and mac-os?

No! I have not used any new libs or methods.

> documentation for add() & clip()

Basic documentation is [here](https://github.com/bookiza/bookiza/pull/6/files#diff-7cbd01aa7ee90546a0af834b3590af52), see lines 94/95 of commands.js.

> test suite

Yeah this will be great in time!

**Pull request merged**
